$content = Get-Content "E:\WABA\frontend\src\pages\Dashboard.jsx" -Raw -Encoding UTF8
$content = $content -replace '🏥', ''
$content = $content -replace '📋', ''
$content = $content -replace '📅', ''
$content = $content -replace '📆', ''
$content = $content -replace '📨', ''
$content = $content -replace '🔄', ''
$content = $content -replace '📊', ''
$content = $content -replace '✅', ''
$content = $content -replace '❌', ''
$content = $content -replace '🎫', ''
$content = $content -replace '👤', ''
$content = $content -replace '📞', ''
$content = $content -replace '👨⚕️', ''
$content = $content -replace '🕐', ''
$content = $content -replace '⏳', ''
$content = $content -replace '📭', ''
$content = $content -replace '✏️', ''
$content = $content -replace '🗑️', ''
$content = $content -replace '📤', ''
$content = $content -replace '👥', ''
$content = $content -replace '✕', 'X'
Set-Content "E:\WABA\frontend\src\pages\Dashboard.jsx" $content -Encoding UTF8
Write-Host "Emojis removed successfully!"
